import os

schema_path = r"c:\Users\surji\HPE_CPP49\backend\schema_store\enriched_schema.yaml"

sqlp_yaml = """
sqlp:
  source_file: measurefiles/sqlpcsv
  ddl_record: ZMSSQLP
  entity_type: SQLPROC
  purpose: 'The SQLPROC entity provides information about one or more SQL processes. There is one SQLPROC counter record for each SQL process.'
  identity_columns:
  - process_name
  - pin
  - cpu_num
  time_columns:
  - from_timestamp
  - to_timestamp
  - delta_time
  join_hints:
  - JOIN proc ON (system_name, cpu_num, pin, from_timestamp) for basic process metrics
  - JOIN sqls ON (system_name, cpu_num, pin, from_timestamp) for statement metrics
  columns:
    system_name:
      queryable: true
      type: string
      description: NonStop node name. Name of the system on which the measurement was taken.
    cpu_num:
      queryable: true
      type: integer
      description: Number of the CPU on which the SQL process is running.
    pin:
      queryable: true
      type: integer
      description: Process identification number of the measured SQL process.
    process_name:
      queryable: true
      type: string
      description: Name of the SQL process.
    from_timestamp:
      queryable: true
      type: datetime
      description: Measurement interval start
    to_timestamp:
      queryable: true
      type: datetime
      description: Measurement interval end
    delta_time:
      queryable: true
      type: integer
      unit: microseconds
      description: Interval duration
    sql_obj_recompiles:
      queryable: true
      type: integer
      counter_type: Incrementing
      description: Number of objects recompiled for this process.
    sql_obj_recompile_time:
      queryable: true
      type: integer
      unit: microseconds
      counter_type: Elapsed
      description: Time this process spent recompiling objects.
    sql_stmt_recompiles:
      queryable: true
      type: integer
      counter_type: Incrementing
      description: Number of statements recompiled for this process.
    sql_stmt_recompile_time:
      queryable: true
      type: integer
      unit: microseconds
      counter_type: Elapsed
      description: Time this process spent recompiling statements.
    sql_newprocesses:
      queryable: true
      type: integer
      counter_type: Incrementing
      description: Number of NEWPROCESS calls generated by the SQL executor on behalf of this process.
    sql_newprocess_time:
      queryable: true
      type: integer
      unit: microseconds
      counter_type: Elapsed
      description: Time this process spent executing SQL-NEWPROCESS.
    opens:
      queryable: true
      type: integer
      counter_type: Incrementing
      description: Number of OPEN calls performed by the SQL executor on behalf of this process.
    open_time:
      queryable: true
      type: integer
      unit: microseconds
      counter_type: Elapsed
      description: Time this process spent executing OPENs.
    sql_stmt_compiles:
      queryable: true
      type: integer
      counter_type: Incrementing
      description: Number of SQL dynamic statements compiled for this process.
    sql_stmt_compile_time:
      queryable: true
      type: integer
      unit: microseconds
      counter_type: Elapsed
      description: Time this process spent on SQL dynamic statement compilations.

sqls:
  source_file: measurefiles/sqlscsv
  ddl_record: ZMSSQLS
  entity_type: SQLSTMT
  purpose: 'The SQLSTMT entity provides information about all SQL statements within the SQL process. There is one SQLSTMT counter record for each SQL statement in each procedure or module of a program that contains SQL function.'
  identity_columns:
  - process_name
  - run_unit
  - statement_index
  time_columns:
  - from_timestamp
  - to_timestamp
  - delta_time
  join_hints:
  - JOIN sqlp ON (system_name, cpu_num, pin, from_timestamp) for process-level SQL metrics
  columns:
    system_name:
      queryable: true
      type: string
      description: NonStop node name. Name of the system on which the measurement was taken.
    cpu_num:
      queryable: true
      type: integer
      description: CPU number on which the statement executed
    pin:
      queryable: true
      type: integer
      description: Process identification number
    process_name:
      queryable: true
      type: string
      description: Name of the process that contains the SQL statements
    run_unit:
      queryable: true
      type: string
      description: Name of the procedure that contains the measured SQL statement.
    statement_index:
      queryable: true
      type: integer
      description: Index number of the statement.
    from_timestamp:
      queryable: true
      type: datetime
      description: Measurement interval start
    to_timestamp:
      queryable: true
      type: datetime
      description: Measurement interval end
    delta_time:
      queryable: true
      type: integer
      unit: microseconds
      description: Interval duration
    calls:
      queryable: true
      type: integer
      counter_type: Incrementing
      description: Number of times the measured SQL statement was executed.
    elapsed_busy_time:
      queryable: true
      type: integer
      unit: microseconds
      counter_type: Elapsed
      description: Time the process spent executing the measured SQL statement.
    records_used:
      queryable: true
      type: integer
      counter_type: Accumulating
      description: Number of records inserted, updated, deleted, or read by the SQL executor through this statement.
    records_accessed:
      queryable: true
      type: integer
      counter_type: Accumulating
      description: Number of records accessed by the disk process or file system to evaluate this statement.
    disc_reads:
      queryable: true
      type: integer
      counter_type: Incrementing
      description: Number of physical disk reads performed for this statement.
    messages:
      queryable: true
      type: integer
      counter_type: Incrementing
      description: Number of messages sent by the system on behalf of this statement.
    message_bytes:
      queryable: true
      type: integer
      unit: bytes
      counter_type: Accumulating
      description: Number of message bytes sent for this statement by the system.
    sorts:
      queryable: true
      type: integer
      counter_type: Incrementing
      description: Number of times an external sort process was invoked for this statement.
    elapsed_sort_time:
      queryable: true
      type: integer
      unit: microseconds
      counter_type: Elapsed
      description: Time spent by the process on sorts for this statement.
    recompiles:
      queryable: true
      type: integer
      counter_type: Incrementing
      description: Number of times the statement was recompiled.
    elapsed_recompile_time:
      queryable: true
      type: integer
      unit: microseconds
      counter_type: Elapsed
      description: Time the process spent recompiling this statement.
    lock_waits:
      queryable: true
      type: integer
      counter_type: Incrementing
      description: Number of times this statement waited for a lock request.
    timeouts:
      queryable: true
      type: integer
      counter_type: Incrementing
      description: Number of times a request timed out. A timeout is caused by either a lock-wait or a congested disk process or network.
    escalations:
      queryable: true
      type: integer
      counter_type: Incrementing
      description: Number of times a record lock was escalated to a file lock.
"""

with open(schema_path, "a") as f:
    f.write(sqlp_yaml)

print("Appended sqlp and sqls to schema.")
