import yaml
import os

schema_path = r'c:\Users\surji\HPE_CPP49\docs\reference\measure_schema.yaml'
with open(schema_path, 'r', encoding='utf-8') as f:
    content = f.read()

content = content.replace('{N}', '[n]')

sql_schema = '''
sqlp:
  source_file: measurefiles/sqlpcsv
  ddl_record: ZMSSQLP
  entity_type: SQLP (SQL Process)
  purpose: >
    Per-process SQL executor performance metrics. Captures object and statement recompilations,
    new process creations, and open calls initiated by the SQL executor.
  identity_columns: [system_name, cpu_num, pin, process_name]
  time_columns: [from_timestamp, to_timestamp, delta_time]
  join_hints:
    - "JOIN proc ON (system_name, cpu_num, pin, from_timestamp) for process activity"
  columns:
    u_loadid.loadid:              { queryable: false }
    u_loadid.load_id.prefix_id:   { queryable: false }
    u_loadid.load_id.interval_id: { queryable: false }
    system_name:       { queryable: true,  type: string }
    cpu_num:           { queryable: true,  type: integer }
    os_version.letter: { queryable: true,  type: string }
    os_version.number: { queryable: true,  type: string }
    object_uid:        { queryable: false }
    from_timestamp:    { queryable: true,  type: datetime }
    to_timestamp:      { queryable: true,  type: datetime }
    delta_time:        { queryable: true,  type: integer, unit: microseconds }
    template_version:      { queryable: false }
    format_version.letter: { queryable: false }
    format_version.number: { queryable: false }
    data_version.letter:   { queryable: false }
    data_version.number:   { queryable: false }
    subsystem_version:     { queryable: false }
    error:                 { queryable: false }

    pin: { queryable: true, type: integer, description: "Process identification number" }
    priority: { queryable: true, type: integer, description: "Creation priority of the process" }
    userid.group: { queryable: true, type: integer, description: "Process accessor ID group" }
    userid.user: { queryable: true, type: integer, description: "Process accessor ID user" }
    creatorid.group: { queryable: true, type: integer, description: "Creator access ID group" }
    creatorid.user: { queryable: true, type: integer, description: "Creator access ID user" }
    process_name: { queryable: true, type: string, description: "Name of the SQL process" }
    program_file_name.volume: { queryable: true, type: string, description: "Volume component of the program file" }
    program_file_name.subvol: { queryable: true, type: string, description: "Subvolume component of the program file" }
    program_file_name.filename: { queryable: true, type: string, description: "Filename component of the program file" }
    osspid: { queryable: true, type: integer, description: "OSS process ID" }
    ancestor_cpu: { queryable: true, type: integer, description: "CPU of the ancestor process" }
    ancestor_pin: { queryable: true, type: integer, description: "PIN of the ancestor process" }
    ancestor_sysname: { queryable: true, type: string, description: "System of the ancestor process" }
    ancestor_process_name: { queryable: true, type: string, description: "Name of the ancestor process" }
    device_name: { queryable: true, type: string, description: "Disk device of the program file" }
    program_file_name_mid.pathid: { queryable: false }
    program_file_name_mid.crvsn: { queryable: false }
    u_gmom.gmom.gmom_node: { queryable: false }
    u_gmom.gmom.gmom_cpu: { queryable: false }
    u_gmom.gmom.gmom_pin: { queryable: false }
    u_gmom.gmom.gmom_jobid: { queryable: false }
    gmom_sysname: { queryable: true, type: string, description: "GMOM node system name" }
    gmom_process_name: { queryable: true, type: string, description: "GMOM process name" }

    sql_obj_recompiles: { queryable: true, type: integer, counter_type: Incrementing, description: "Number of objects recompiled for this process" }
    sql_obj_recompile_time: { queryable: true, type: integer, counter_type: Busy, description: "Time this process spent recompiling objects" }
    sql_stmt_recompiles: { queryable: true, type: integer, counter_type: Incrementing, description: "Number of statements recompiled" }
    sql_stmt_recompile_time: { queryable: true, type: integer, counter_type: Busy, description: "Time spent recompiling statements" }
    sql_newprocesses: { queryable: true, type: integer, counter_type: Incrementing, description: "Number of NEWPROCESS calls generated by the SQL executor" }
    sql_newprocess_time: { queryable: true, type: integer, counter_type: Busy, description: "Time spent executing SQL-NEWPROCESS" }
    opens: { queryable: true, type: integer, counter_type: Incrementing, description: "Number of OPEN calls performed by the SQL executor" }
    open_time: { queryable: true, type: integer, counter_type: Busy, description: "Time spent executing OPENs" }
    sql_stmt_compiles: { queryable: true, type: integer, counter_type: Incrementing, description: "Number of SQL dynamic statements compiled" }
    sql_stmt_compile_time: { queryable: true, type: integer, counter_type: Busy, description: "Time spent on SQL dynamic statement compilations" }

sqls:
  source_file: measurefiles/sqlscsv
  ddl_record: ZMSSQLS
  entity_type: SQLS (SQL Statement)
  purpose: >
    Per-statement SQL executor performance metrics. Captures calls, execution time,
    records used/accessed, disc reads, sorts, lock waits, and recompilations for each
    measured SQL statement within a process.
  identity_columns: [system_name, cpu_num, pin, process_name, statement_index, run_unit]
  time_columns: [from_timestamp, to_timestamp, delta_time]
  join_hints:
    - "JOIN proc ON (system_name, cpu_num, pin, from_timestamp) for process context"
    - "JOIN sqlp ON (system_name, cpu_num, pin, from_timestamp) for executor context"
  columns:
    u_loadid.loadid:              { queryable: false }
    u_loadid.load_id.prefix_id:   { queryable: false }
    u_loadid.load_id.interval_id: { queryable: false }
    system_name:       { queryable: true,  type: string }
    cpu_num:           { queryable: true,  type: integer }
    os_version.letter: { queryable: true,  type: string }
    os_version.number: { queryable: true,  type: string }
    object_uid:        { queryable: false }
    from_timestamp:    { queryable: true,  type: datetime }
    to_timestamp:      { queryable: true,  type: datetime }
    delta_time:        { queryable: true,  type: integer, unit: microseconds }
    template_version:      { queryable: false }
    format_version.letter: { queryable: false }
    format_version.number: { queryable: false }
    data_version.letter:   { queryable: false }
    data_version.number:   { queryable: false }
    subsystem_version:     { queryable: false }
    error:                 { queryable: false }

    pin: { queryable: true, type: integer, description: "Process identification number" }
    priority: { queryable: true, type: integer, description: "Creation priority of the process" }
    userid.group: { queryable: true, type: integer, description: "Process accessor ID group" }
    userid.user: { queryable: true, type: integer, description: "Process accessor ID user" }
    creatorid.group: { queryable: true, type: integer, description: "Creator access ID group" }
    creatorid.user: { queryable: true, type: integer, description: "Creator access ID user" }
    process_name: { queryable: true, type: string, description: "Name of the SQL process" }
    program_file_name.volume: { queryable: true, type: string, description: "Volume component of the program file" }
    program_file_name.subvol: { queryable: true, type: string, description: "Subvolume component of the program file" }
    program_file_name.filename: { queryable: true, type: string, description: "Filename component of the program file" }
    osspid: { queryable: true, type: integer, description: "OSS process ID" }
    ancestor_cpu: { queryable: true, type: integer, description: "CPU of the ancestor process" }
    ancestor_pin: { queryable: true, type: integer, description: "PIN of the ancestor process" }
    ancestor_sysname: { queryable: true, type: string, description: "System of the ancestor process" }
    ancestor_process_name: { queryable: true, type: string, description: "Name of the ancestor process" }
    device_name: { queryable: true, type: string, description: "Disk device of the program file" }
    program_file_name_mid.pathid: { queryable: false }
    program_file_name_mid.crvsn: { queryable: false }
    statement_index: { queryable: true, type: integer, description: "Statement index number (0-255) within the specified run unit" }
    u_gmom.gmom.gmom_node: { queryable: false }
    u_gmom.gmom.gmom_cpu: { queryable: false }
    u_gmom.gmom.gmom_pin: { queryable: false }
    u_gmom.gmom.gmom_jobid: { queryable: false }
    gmom_sysname: { queryable: true, type: string, description: "GMOM node system name" }
    gmom_process_name: { queryable: true, type: string, description: "GMOM process name" }
    version: { queryable: true, type: integer, description: "Record version" }
    creator_type: { queryable: true, type: integer, description: "Creator type (1 = SQL/MP, 2 = SQL/MX 1.x, 3 = SQL/MX 2.x)" }
    run_unit_len: { queryable: true, type: integer, description: "Length of the RUN-UNIT field" }
    run_unit: { queryable: true, type: string, description: "Left-justified external-format ANSI SQL name" }

    calls: { queryable: true, type: integer, counter_type: Incrementing, description: "Number of times the measured SQL statement was executed" }
    elapsed_busy_time: { queryable: true, type: integer, counter_type: Busy, description: "Time the process spent executing the measured SQL statement" }
    records_used: { queryable: true, type: integer, counter_type: Accumulating, description: "Number of records inserted, updated, deleted, or read" }
    records_accessed: { queryable: true, type: integer, counter_type: Accumulating, description: "Number of records accessed by the disk process or file system" }
    disc_reads: { queryable: true, type: integer, counter_type: Incrementing, description: "Number of physical disk reads performed for this statement" }
    messages: { queryable: true, type: integer, counter_type: Incrementing, description: "Number of messages sent by the system" }
    message_bytes: { queryable: true, type: integer, counter_type: Accumulating, description: "Number of message bytes sent" }
    sorts: { queryable: true, type: integer, counter_type: Incrementing, description: "Number of times an external sort process was invoked" }
    elapsed_sort_time: { queryable: true, type: integer, counter_type: Busy, description: "Time spent on sorts" }
    recompiles: { queryable: true, type: integer, counter_type: Incrementing, description: "Number of times the statement was recompiled" }
    elapsed_recompile_time: { queryable: true, type: integer, counter_type: Busy, description: "Time spent recompiling this statement" }
    lock_waits: { queryable: true, type: integer, counter_type: Incrementing, description: "Number of times this statement waited for a lock request" }
    timeouts: { queryable: true, type: integer, counter_type: Incrementing, description: "Number of times a request timed out" }
    escalations: { queryable: true, type: integer, counter_type: Incrementing, description: "Number of times a record lock was escalated to a file lock" }
'''

business_rules = '''business_rules: >
  PROCESS NAME CONVENTIONS: ALL processes in this dataset start
  with '$'. There are NO processes without a '$' prefix. 
  Disk processes match LIKE '$DATA%' OR '$SSD%' OR '$AUDIT%'.
  Core system processes are: $SYSTEM, $MONITOR, $MSENGER, $VIRTUAL, $NULL,
  $OSS, $SWAP, $SWAP01, $SWAP23, $SWAP34, $NCP, $TMP.
  User/application processes are everything else (e.g. $BEER, $CHAMP, $GANESH).
  When categorising processes, always use explicit IN() or LIKE patterns.
  When using variables denoted by [n] (like ipu[n] or c[n]), you MUST expand
  them dynamically using the index bounds provided in the database mapping configuration.
  For example, if bounds are 0 to 15, ipu[n] should be ipu0, ipu1... ipu15.

'''

final_content = business_rules + content + "\n" + sql_schema

target = r'c:\Users\surji\HPE_CPP49\backend\schema_store\enriched_schema.yaml'
with open(target, 'w', encoding='utf-8') as f:
    f.write(final_content)
print('Done!')
